

python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltag_1_detection.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_detection.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_new_detection.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p1_detection.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p2_detection.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p3_detection.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltag_1_detection_erosion.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_detection_erosion.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_new_detection_erosion.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p1_detection_erosion.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p2_detection_erosion.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p3_detection_erosion.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltag_1_detection_erosion_nofp_shape.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_detection_erosion_nofp_shape.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_new_detection_erosion_nofp_shape.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p1_detection_erosion_nofp_shape.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p2_detection_erosion_nofp_shape.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p3_detection_erosion_nofp_shape.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltag_1_detection_erosion_nofp_shape_filtering.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_new_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p1_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p2_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p3_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltag_1_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_new_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p1_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p2_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p3_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p3_ground_truth.json