#!/bin/bash

python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltag_1_detection.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_detection.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_new_detection.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p1_detection.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p2_detection.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection/apriltags_p3_detection.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltag_1_detection_erosion.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_detection_erosion.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_new_detection_erosion.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p1_detection_erosion.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p2_detection_erosion.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion/apriltags_p3_detection_erosion.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltag_1_detection_erosion_nofp_shape.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_detection_erosion_nofp_shape.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_new_detection_erosion_nofp_shape.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p1_detection_erosion_nofp_shape.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p2_detection_erosion_nofp_shape.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape/apriltags_p3_detection_erosion_nofp_shape.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltag_1_detection_erosion_nofp_shape_filtering.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_new_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p1_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p2_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering/apriltags_p3_detection_erosion_nofp_shape_filtering.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltag_1_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_new_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p1_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p2_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py apriltags_lib_detection_erosion_nofp_shape_filtering_dark_only/apriltags_p3_detection_erosion_nofp_shape_filtering_dark_only.json ground_truth/apriltags_p3_ground_truth.json





python3 tp_tn_fp_fn.py pupil_detection/apriltag_1_detection_pupil.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection/apriltags_p0_detection_pupil.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection/apriltags_new_detection_pupil.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection/apriltags_p1_detection_pupil.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection/apriltags_p2_detection_pupil.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection/apriltags_p3_detection_pupil.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltag_1_detection_pupil_threshold.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltags_p0_detection_pupil_threshold.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltags_new_detection_pupil_threshold.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltags_p1_detection_pupil_threshold.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltags_p2_detection_pupil_threshold.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold/apriltags_p3_detection_pupil_threshold.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltag_1_detection_pupil_shape2.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltags_p0_detection_pupil_shape2.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltags_new_detection_pupil_shape2.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltags_p1_detection_pupil_shape2.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltags_p2_detection_pupil_shape2.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_shape2/apriltags_p3_detection_pupil_shape2.json ground_truth/apriltags_p3_ground_truth.json

python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltag_1_detection_pupil_threshold_shape2.json ground_truth/apriltag_1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltags_p0_detection_pupil_threshold_shape2.json ground_truth/apriltags_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltags_new_detection_pupil_threshold_shape2.json ground_truth/apriltags_new_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltags_p1_detection_pupil_threshold_shape2.json ground_truth/apriltags_p1_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltags_p2_detection_pupil_threshold_shape2.json ground_truth/apriltags_p2_ground_truth.json
python3 tp_tn_fp_fn.py pupil_detection_threshold_shape2/apriltags_p3_detection_pupil_threshold_shape2.json ground_truth/apriltags_p3_ground_truth.json




python3 tp_tn_fp_fn.py neurnal_network_finetuned/apriltags_p3_finetuned.json ground_truth/apriltags_p3_ground_truth.json
python3 tp_tn_fp_fn.py neurnal_network_trained_on_our_videos/apriltags_p3_trained_on_our_videos.json ground_truth/apriltags_p3_ground_truth.json
python3 tp_tn_fp_fn.py neurnal_network_trained_on_web_images/apriltags_p3_trained_on_web_images.json ground_truth/apriltags_p3_ground_truth.json

python3 put_results_into_single_json_file.py all_results.json